name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
projects: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

  - type: input
    id: name
    attributes:
      label: What is your name?
      placeholder: ex. Sertha Taweewattana
    validations:
      required: true

  - type: dropdown
    id: request-type
    attributes:
      label: Type of request?
      options:
        - New Feature
        - Improvement
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: What is the OS which you want to suggest?
      placeholder: ex. Windows 11 / macOS / Linux
    validations:
      required: false

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion details
      description: Please describe the feature you'd like to see added.
      placeholder: Tell us your idea!
    validations:
      required: true